version: "3.8"

services:
  application:
    container_name: fastapi-app
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi-app
    ports:
      - "8000:8000"
  
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    expose:
      - "5432"

  postgres-test:
    container_name: postgres-test
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - 5433:5432
    expose:
      - "5433"