version: "3.8"

services:
  application:
    container_name: fastapi-app
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi-app
    ports:
      - "8000:8000"
  
  mongod:
    image: mongo:5.0.15
    ports:
      - "27017:27017"